name: Automated tests

on: 
  pull_request
    branches:
      - master
jobs:
  python-tests:
    name: Pytest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run Pytest Tests
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=test